blank_issues_enabled: true
contact_links: 
  - name: "Report an issue"
    about: "For when Collect is behaving in an unexpected way"
    url: "https://forum.getodk.org/c/support/6"
  - name: "Request a feature"
    about: "For when Collect is missing functionality"
    url: "https://forum.getodk.org/c/features/9"
  - name: "Everything else"
    about: "For everything else"
    url: "https://forum.getodk.org/c/support/6"